name: Integration tests

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  run:
    name: Run integration tests
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Database
        run:  docker-compose up -d --build

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache-dependency-path: go.sum

      - name: Test
        run: |
          sleep 5 && go test -v -cover --race --tags="integration_tests" ./...